


SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;


COMMENT ON SCHEMA "public" IS 'standard public schema';



CREATE EXTENSION IF NOT EXISTS "pg_graphql" WITH SCHEMA "graphql";






CREATE EXTENSION IF NOT EXISTS "pg_stat_statements" WITH SCHEMA "extensions";






CREATE EXTENSION IF NOT EXISTS "pgcrypto" WITH SCHEMA "extensions";






CREATE EXTENSION IF NOT EXISTS "supabase_vault" WITH SCHEMA "vault";






CREATE EXTENSION IF NOT EXISTS "uuid-ossp" WITH SCHEMA "extensions";





SET default_tablespace = '';

SET default_table_access_method = "heap";


CREATE TABLE IF NOT EXISTS "public"."brand_blacklists" (
    "user_id" integer NOT NULL,
    "brand_id" integer NOT NULL
);


ALTER TABLE "public"."brand_blacklists" OWNER TO "postgres";


CREATE TABLE IF NOT EXISTS "public"."brands" (
    "brand_id" integer NOT NULL,
    "name" character varying(255) NOT NULL
);


ALTER TABLE "public"."brands" OWNER TO "postgres";


ALTER TABLE "public"."brands" ALTER COLUMN "brand_id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."brands_brand_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."categories" (
    "category_id" integer NOT NULL,
    "name" character varying(255) NOT NULL
);


ALTER TABLE "public"."categories" OWNER TO "postgres";


ALTER TABLE "public"."categories" ALTER COLUMN "category_id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."categories_category_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."deals" (
    "deal_id" integer NOT NULL,
    "item_id" integer NOT NULL,
    "original_price" numeric(10,2) NOT NULL,
    "on_sale" boolean DEFAULT false NOT NULL,
    "sale_price" numeric(10,2),
    "membership_sale" boolean DEFAULT false,
    "membership_price" numeric(10,2),
    "last_fetched" timestamp without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL
);


ALTER TABLE "public"."deals" OWNER TO "postgres";


CREATE SEQUENCE IF NOT EXISTS "public"."deals_deal_id_seq"
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE "public"."deals_deal_id_seq" OWNER TO "postgres";


ALTER SEQUENCE "public"."deals_deal_id_seq" OWNED BY "public"."deals"."deal_id";



CREATE TABLE IF NOT EXISTS "public"."favorite_products" (
    "user_id" integer NOT NULL,
    "product_id" integer NOT NULL
);


ALTER TABLE "public"."favorite_products" OWNER TO "postgres";


CREATE TABLE IF NOT EXISTS "public"."items" (
    "item_id" integer NOT NULL,
    "product_id" integer NOT NULL,
    "store_item_id" integer NOT NULL,
    "avg_rating" numeric(3,2) DEFAULT 0.00,
    "rating_count" integer DEFAULT 0,
    "package_quantity" integer,
    "unit_id" integer,
    "store_source" "text" NOT NULL
);


ALTER TABLE "public"."items" OWNER TO "postgres";


ALTER TABLE "public"."items" ALTER COLUMN "item_id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."items_item_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."products" (
    "product_id" integer NOT NULL,
    "name" character varying(255) NOT NULL,
    "brand_id" integer,
    "category_id" integer,
    "unit_id" integer,
    "ebt_eligible" boolean
);


ALTER TABLE "public"."products" OWNER TO "postgres";


ALTER TABLE "public"."products" ALTER COLUMN "product_id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."products_product_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."saved_deals" (
    "user_id" integer NOT NULL,
    "deal_id" integer NOT NULL
);


ALTER TABLE "public"."saved_deals" OWNER TO "postgres";


CREATE TABLE IF NOT EXISTS "public"."search_history" (
    "user_id" integer NOT NULL,
    "search_query" "text" NOT NULL,
    "search_time" timestamp without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL
);


ALTER TABLE "public"."search_history" OWNER TO "postgres";


CREATE TABLE IF NOT EXISTS "public"."store_addresses" (
    "store_source" "text" NOT NULL,
    "address" "text" NOT NULL
);


ALTER TABLE "public"."store_addresses" OWNER TO "postgres";


CREATE TABLE IF NOT EXISTS "public"."store_blacklists" (
    "user_id" integer NOT NULL,
    "store_source" "text" NOT NULL
);


ALTER TABLE "public"."store_blacklists" OWNER TO "postgres";


CREATE TABLE IF NOT EXISTS "public"."store_memberships" (
    "user_id" integer NOT NULL,
    "membership_id" character varying(100),
    "is_active" boolean DEFAULT true NOT NULL,
    "store_source" "text" NOT NULL
);


ALTER TABLE "public"."store_memberships" OWNER TO "postgres";


CREATE TABLE IF NOT EXISTS "public"."stores" (
    "store_source" "text" NOT NULL,
    "accepts_ebt" boolean,
    "offers_delivery" boolean,
    "url" character varying NOT NULL
);


ALTER TABLE "public"."stores" OWNER TO "postgres";


CREATE TABLE IF NOT EXISTS "public"."test_table" (
    "id" integer NOT NULL,
    "name" "text"
);


ALTER TABLE "public"."test_table" OWNER TO "postgres";


CREATE SEQUENCE IF NOT EXISTS "public"."test_table_id_seq"
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE "public"."test_table_id_seq" OWNER TO "postgres";


ALTER SEQUENCE "public"."test_table_id_seq" OWNED BY "public"."test_table"."id";



CREATE TABLE IF NOT EXISTS "public"."units" (
    "unit_id" integer NOT NULL,
    "name" character varying(50) NOT NULL,
    "unit_type" "text"
);


ALTER TABLE "public"."units" OWNER TO "postgres";


ALTER TABLE "public"."units" ALTER COLUMN "unit_id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."units_unit_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."users" (
    "user_id" integer NOT NULL,
    "email" "text" NOT NULL,
    "name" "text",
    "send_notifications" boolean DEFAULT true NOT NULL
);


ALTER TABLE "public"."users" OWNER TO "postgres";


CREATE SEQUENCE IF NOT EXISTS "public"."users_user_id_seq"
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE "public"."users_user_id_seq" OWNER TO "postgres";


ALTER SEQUENCE "public"."users_user_id_seq" OWNED BY "public"."users"."user_id";



ALTER TABLE ONLY "public"."deals" ALTER COLUMN "deal_id" SET DEFAULT "nextval"('"public"."deals_deal_id_seq"'::"regclass");



ALTER TABLE ONLY "public"."test_table" ALTER COLUMN "id" SET DEFAULT "nextval"('"public"."test_table_id_seq"'::"regclass");



ALTER TABLE ONLY "public"."users" ALTER COLUMN "user_id" SET DEFAULT "nextval"('"public"."users_user_id_seq"'::"regclass");



ALTER TABLE ONLY "public"."brand_blacklists"
    ADD CONSTRAINT "brand_blacklists_pkey" PRIMARY KEY ("user_id", "brand_id");



ALTER TABLE ONLY "public"."brands"
    ADD CONSTRAINT "brands_pkey" PRIMARY KEY ("brand_id");



ALTER TABLE ONLY "public"."categories"
    ADD CONSTRAINT "categories_pkey" PRIMARY KEY ("category_id");



ALTER TABLE ONLY "public"."deals"
    ADD CONSTRAINT "deals_pkey" PRIMARY KEY ("deal_id");



ALTER TABLE ONLY "public"."favorite_products"
    ADD CONSTRAINT "favorite_products_pkey" PRIMARY KEY ("user_id", "product_id");



ALTER TABLE ONLY "public"."items"
    ADD CONSTRAINT "items_pkey" PRIMARY KEY ("item_id");



ALTER TABLE ONLY "public"."items"
    ADD CONSTRAINT "items_store_item_id_key" UNIQUE ("store_item_id");



ALTER TABLE ONLY "public"."products"
    ADD CONSTRAINT "products_name_key" UNIQUE ("name");



ALTER TABLE ONLY "public"."products"
    ADD CONSTRAINT "products_pkey" PRIMARY KEY ("product_id");



ALTER TABLE ONLY "public"."store_addresses"
    ADD CONSTRAINT "store_addresses_pkey" PRIMARY KEY ("address");



ALTER TABLE ONLY "public"."store_blacklists"
    ADD CONSTRAINT "store_blacklists_pkey" PRIMARY KEY ("user_id");



ALTER TABLE ONLY "public"."store_memberships"
    ADD CONSTRAINT "store_memberships_pkey" PRIMARY KEY ("user_id");



ALTER TABLE ONLY "public"."stores"
    ADD CONSTRAINT "stores_pkey" PRIMARY KEY ("store_source");



ALTER TABLE ONLY "public"."test_table"
    ADD CONSTRAINT "test_table_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."units"
    ADD CONSTRAINT "units_pkey" PRIMARY KEY ("unit_id");



ALTER TABLE ONLY "public"."users"
    ADD CONSTRAINT "users_email_key" UNIQUE ("email");



ALTER TABLE ONLY "public"."users"
    ADD CONSTRAINT "users_pkey" PRIMARY KEY ("user_id");



ALTER TABLE ONLY "public"."brand_blacklists"
    ADD CONSTRAINT "brand_blacklists_brand_id_fkey" FOREIGN KEY ("brand_id") REFERENCES "public"."brands"("brand_id") ON DELETE CASCADE;



ALTER TABLE ONLY "public"."brand_blacklists"
    ADD CONSTRAINT "brand_blacklists_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "public"."users"("user_id") ON DELETE CASCADE;



ALTER TABLE ONLY "public"."favorite_products"
    ADD CONSTRAINT "favorite_products_product_id_fkey" FOREIGN KEY ("product_id") REFERENCES "public"."products"("product_id") ON DELETE CASCADE;



ALTER TABLE ONLY "public"."favorite_products"
    ADD CONSTRAINT "favorite_products_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "public"."users"("user_id") ON DELETE CASCADE;



ALTER TABLE ONLY "public"."items"
    ADD CONSTRAINT "fk_items_unit" FOREIGN KEY ("unit_id") REFERENCES "public"."units"("unit_id");



ALTER TABLE ONLY "public"."items"
    ADD CONSTRAINT "items_product_id_fkey" FOREIGN KEY ("product_id") REFERENCES "public"."products"("product_id") ON DELETE CASCADE;



ALTER TABLE ONLY "public"."items"
    ADD CONSTRAINT "items_store_source_fkey" FOREIGN KEY ("store_source") REFERENCES "public"."stores"("store_source");



ALTER TABLE ONLY "public"."products"
    ADD CONSTRAINT "products_brand_id_fkey" FOREIGN KEY ("brand_id") REFERENCES "public"."brands"("brand_id");



ALTER TABLE ONLY "public"."products"
    ADD CONSTRAINT "products_category_id_fkey" FOREIGN KEY ("category_id") REFERENCES "public"."categories"("category_id");



ALTER TABLE ONLY "public"."products"
    ADD CONSTRAINT "products_unit_id_fkey" FOREIGN KEY ("unit_id") REFERENCES "public"."units"("unit_id");



ALTER TABLE ONLY "public"."saved_deals"
    ADD CONSTRAINT "saved_deals_deal_id_fkey" FOREIGN KEY ("deal_id") REFERENCES "public"."deals"("deal_id") ON DELETE CASCADE;



ALTER TABLE ONLY "public"."saved_deals"
    ADD CONSTRAINT "saved_deals_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "public"."users"("user_id") ON DELETE CASCADE;



ALTER TABLE ONLY "public"."search_history"
    ADD CONSTRAINT "search_history_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "public"."users"("user_id") ON DELETE CASCADE;



ALTER TABLE ONLY "public"."store_addresses"
    ADD CONSTRAINT "store_addresses_store_source_fkey" FOREIGN KEY ("store_source") REFERENCES "public"."stores"("store_source");



ALTER TABLE ONLY "public"."store_blacklists"
    ADD CONSTRAINT "store_blacklists_store_source_fkey" FOREIGN KEY ("store_source") REFERENCES "public"."stores"("store_source");



ALTER TABLE ONLY "public"."store_blacklists"
    ADD CONSTRAINT "store_blacklists_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "public"."users"("user_id") ON DELETE CASCADE;



ALTER TABLE ONLY "public"."store_memberships"
    ADD CONSTRAINT "store_memberships_store_source_fkey" FOREIGN KEY ("store_source") REFERENCES "public"."stores"("store_source");



ALTER TABLE ONLY "public"."store_memberships"
    ADD CONSTRAINT "store_memberships_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "public"."users"("user_id");





ALTER PUBLICATION "supabase_realtime" OWNER TO "postgres";


GRANT USAGE ON SCHEMA "public" TO "postgres";
GRANT USAGE ON SCHEMA "public" TO "anon";
GRANT USAGE ON SCHEMA "public" TO "authenticated";
GRANT USAGE ON SCHEMA "public" TO "service_role";








































































































































































GRANT ALL ON TABLE "public"."brand_blacklists" TO "anon";
GRANT ALL ON TABLE "public"."brand_blacklists" TO "authenticated";
GRANT ALL ON TABLE "public"."brand_blacklists" TO "service_role";



GRANT ALL ON TABLE "public"."brands" TO "anon";
GRANT ALL ON TABLE "public"."brands" TO "authenticated";
GRANT ALL ON TABLE "public"."brands" TO "service_role";



GRANT ALL ON SEQUENCE "public"."brands_brand_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."brands_brand_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."brands_brand_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."categories" TO "anon";
GRANT ALL ON TABLE "public"."categories" TO "authenticated";
GRANT ALL ON TABLE "public"."categories" TO "service_role";



GRANT ALL ON SEQUENCE "public"."categories_category_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."categories_category_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."categories_category_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."deals" TO "anon";
GRANT ALL ON TABLE "public"."deals" TO "authenticated";
GRANT ALL ON TABLE "public"."deals" TO "service_role";



GRANT ALL ON SEQUENCE "public"."deals_deal_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."deals_deal_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."deals_deal_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."favorite_products" TO "anon";
GRANT ALL ON TABLE "public"."favorite_products" TO "authenticated";
GRANT ALL ON TABLE "public"."favorite_products" TO "service_role";



GRANT ALL ON TABLE "public"."items" TO "anon";
GRANT ALL ON TABLE "public"."items" TO "authenticated";
GRANT ALL ON TABLE "public"."items" TO "service_role";



GRANT ALL ON SEQUENCE "public"."items_item_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."items_item_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."items_item_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."products" TO "anon";
GRANT ALL ON TABLE "public"."products" TO "authenticated";
GRANT ALL ON TABLE "public"."products" TO "service_role";



GRANT ALL ON SEQUENCE "public"."products_product_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."products_product_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."products_product_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."saved_deals" TO "anon";
GRANT ALL ON TABLE "public"."saved_deals" TO "authenticated";
GRANT ALL ON TABLE "public"."saved_deals" TO "service_role";



GRANT ALL ON TABLE "public"."search_history" TO "anon";
GRANT ALL ON TABLE "public"."search_history" TO "authenticated";
GRANT ALL ON TABLE "public"."search_history" TO "service_role";



GRANT ALL ON TABLE "public"."store_addresses" TO "anon";
GRANT ALL ON TABLE "public"."store_addresses" TO "authenticated";
GRANT ALL ON TABLE "public"."store_addresses" TO "service_role";



GRANT ALL ON TABLE "public"."store_blacklists" TO "anon";
GRANT ALL ON TABLE "public"."store_blacklists" TO "authenticated";
GRANT ALL ON TABLE "public"."store_blacklists" TO "service_role";



GRANT ALL ON TABLE "public"."store_memberships" TO "anon";
GRANT ALL ON TABLE "public"."store_memberships" TO "authenticated";
GRANT ALL ON TABLE "public"."store_memberships" TO "service_role";



GRANT ALL ON TABLE "public"."stores" TO "anon";
GRANT ALL ON TABLE "public"."stores" TO "authenticated";
GRANT ALL ON TABLE "public"."stores" TO "service_role";



GRANT ALL ON TABLE "public"."test_table" TO "anon";
GRANT ALL ON TABLE "public"."test_table" TO "authenticated";
GRANT ALL ON TABLE "public"."test_table" TO "service_role";



GRANT ALL ON SEQUENCE "public"."test_table_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."test_table_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."test_table_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."units" TO "anon";
GRANT ALL ON TABLE "public"."units" TO "authenticated";
GRANT ALL ON TABLE "public"."units" TO "service_role";



GRANT ALL ON SEQUENCE "public"."units_unit_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."units_unit_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."units_unit_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."users" TO "anon";
GRANT ALL ON TABLE "public"."users" TO "authenticated";
GRANT ALL ON TABLE "public"."users" TO "service_role";



GRANT ALL ON SEQUENCE "public"."users_user_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."users_user_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."users_user_id_seq" TO "service_role";









ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES TO "service_role";






ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS TO "service_role";






ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES TO "service_role";































drop extension if exists "pg_net";


